name: nexum_framework
description: A sample command-line application.
version: 0.0.1
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

# Add regular dependencies here.
dependencies:
  bits: ^1.4.0
  path: ^1.9.0
  uuid: ^4.0.0
  meta: ^1.12.0
  collection: ^1.19.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
